config/routes.rb
Rails.application.routes.draw do
  resources :domains do
    resources :emails, only: [:index, :create]
  end
  
  resources :emails, only: [:update, :destroy]
  
  get 'check_email', to: 'emails#check_email'

  root 'domains#index'

end

app/models/domain.rb
class Domain < ActiveRecord::Base
  has_many :emails, inverse_of: :domain
  validates :name, presence: true, length: { maximum: 64 }, uniqueness: { case_sensitive: false },
            format: { with: /\A[a-zA-Z0-9]+([\-\.]{1}[a-zA-Z0-9]+)*\.[a-zA-Z]{2,13}\z/ }
  validates :quota, numericality: { only_integer: true , greater_than_or_equal_to: 1, less_than_or_equal_to: 1000 }
end

app/models/email.rb
class Email < ActiveRecord::Base
  belongs_to :domain, inverse_of: :emails
  attr_accessor :confirmation_password
  
  before_validation :set_email_address, on: :create
  
  validates :password, presence: true, length: { minimum: 8 }
  validates :username, presence: true, length: { maximum: 104 },
            format: { with: /\A[a-zA-Z0-9]+([_\.\-]?[a-zA-Z0-9]+)*@[a-zA-Z0-9]+([\-\.]{1}[a-zA-Z0-9]+)*\.[a-zA-Z]{2,13}\z/ },
            uniqueness: { case_sensitive: false }

  validates :quota, numericality: { only_integer: true }

  validates :domain, presence: true
  
  default_scope { order(username: :asc) }

  protected
  
  def set_email_address
    self.username += '@' + domain.name
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/domains_controller.rb
class DomainsController < ApplicationController
  before_action :set_domain, only: [:show, :edit, :update, :destroy]
  
  # GET /domains
  # GET /domains.json
  def index
    @domains = Domain.all
  end

  # GET /domains/new
  def new
    @domain = Domain.new
  end
  
  # GET /domains/1/edit
  def edit
  end

  # POST /domains
  # POST /domains.json
  def create
    @domain = Domain.new(domain_params)

    respond_to do |format|
      if @domain.save
        format.html { redirect_to domains_path, notice: 'Domain was successfully created.' }
        format.json { render :show, status: :created, location: @domain }
      else
        format.html { render :new }
        format.json { render json: @domain.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /domains/1
  # PATCH/PUT /domains/1.json
  def update
    respond_to do |format|
      if @domain.update(domain_params)
        format.html { redirect_to domains_path, notice: 'Domain was successfully updated.' }
        format.json { render :show, status: :ok, location: @domain }
      else
        format.html { render :edit }
        format.json { render json: @domain.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /domains/1
  # DELETE /domains/1.json
  def destroy
    @domain.destroy
    respond_to do |format|
      format.html { redirect_to domains_url, notice: 'Domain was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_domain
      @domain = Domain.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def domain_params
      params.require(:domain).permit(:name, :quota)
    end  
end

app/controllers/emails_controller.rb
class EmailsController < ApplicationController
  before_action :set_email, only: [:update, :destroy]
  
  # GET /emails
  def index
    @domain = Domain.find(params[:domain_id])
    @emails = @domain.emails if @domain
  end

  # POST /emails
  def create
    @email = Email.new(email_params)
    @email.domain = Domain.find(params[:domain_id])
    @email_saved = @email.save
  end

  # DELETE /emails/1
  def destroy
    @email_deleted = @email.destroy
  end

  # Checks if an email address is available.
  # If it's available the method returns true in Json format.
  def check_email
    email_address = params[:email][:username] + params[:domain]
    email_available = true
    email_available = false if Email.find_by username: email_address

    respond_to do |format|
      format.json { render :json => email_available }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_email
      @email = Email.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def email_params
      params.require(:email).permit(:username, :quota, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/domains_helper.rb
module DomainsHelper
end

app/helpers/emails_helper.rb
module EmailsHelper
end

app/views/domains/_form.html.erb
<%= form_for(@domain) do |f| %>
  <% if @domain.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@domain.errors.count, "error") %> prohibited this domain from being saved:</h2>

      <ul>
      <% @domain.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :quota %><br>
    <%= f.text_field :quota, class: 'form-control' %>
  </div>

  <button type="submit" class="btn btn-default">Save</button>

<% end %>

app/views/domains/edit.html.erb
<h1>Editing Domain</h1>

<%= render 'form' %>

<br><%= link_to 'Cancel', domains_path, class: 'btn btn-default' %>

app/views/domains/index.html.erb
<table class="table table-bordered table-hover table-striped">
  <thead>
    <tr>
      <th>Domain</th>
      <th>Quota</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @domains.each do |domain| %>
      <tr>
        <td><%= domain.name %></td>
        <td><%= domain.quota %></td>
        <td><%= link_to 'Edit', edit_domain_path(domain), class: 'btn btn-default' %></td>
        <td><%= link_to 'Delete', domain, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %></td>
        <td><%= link_to 'Emails', domain_emails_path(domain), class: 'btn btn-default' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/domains/new.html.erb
<h1>New Domain</h1>

<%= render 'form' %>

<br><%= link_to 'Cancel', domains_path, class: 'btn btn-default' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EmailAdmin</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>  
  <!-- Fixed navbar -->
  <nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to 'Email Admin', root_path, class: 'navbar-brand' %>
      </div>
      <div id="navbar" class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
          <%= content_tag :li, :class => ("active" if current_page?(domains_path)) do
            link_to 'Domains', domains_path
          end %>
          <%= content_tag :li, :class => ("active" if current_page?(new_domain_path)) do
            link_to 'Add Domain', new_domain_path
          end %>
          <%= content_tag :li, :class => ("active" if current_page?(domains_path)) do
            link_to 'Admin Users', domains_path
          end %>
        </ul>
      </div><!--/.nav-collapse -->
    </div>
  </nav>

  <div class="container">
    <div id="alert-messages">
      <% color = 'alert-success' %>
      <% flash.each do |name, message| %>
        <% color = 'alert-danger' if name == :error %>
        <%= content_tag :div, class: "alert #{color} alert-dismissible", role: 'alert' do %>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <%= message %>
        <% end %>
      <% end %>
    </div>

    <%= yield %>
  </div> <!-- /container -->
</body>
</html>